{{ if .Values.service.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-service
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress-service
spec:
  defaultBackend:
    service:
      name: {{ .Chart.Name }}-service
      port:
        number: {{ .Values.service.port }}
  rules:
    - host: {{ .Chart.Name }}-service.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-service
                port:
                  number: {{ .Values.service.port }}
  {{ end }}