apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.database.name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Values.database.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}